sudo: required
language: java
dist: bionic
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
jdk:
- openjdk11
script:
- ".travis/setup.sh"
- ".travis/build.sh"
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then .travis/push.sh; fi
