---
apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  name: default
  namespace: enmasse-infra
spec:
  infraConfigRef: default
  displayName: Default
  shortDescription: Plan allowing for 1 router and 1 broker
  resourceLimits:
    broker: 1.0
    router: 1.0
    aggregate: 2.0
  addressSpaceType: standard
  addressPlans:
    - default-queue
    - default-anycast
    - default-multicast
---
apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: default
  namespace: enmasse-infra
spec:
  admin:
    resources:
      memory: 128Mi
  router:
    linkCapacity: 4
    resources:
      memory: 128Mi
    policy:
      maxConnections: 4
      maxSendersPerConnection: 2
      maxReceiversPerConnection: 2
      maxSessionsPerConnection: 2
  broker:
    resources:
      memory: 256Mi
      storage: 1Gi
    addressFullPolicy: FAIL
---
apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: default-queue
  namespace: enmasse-infra
spec:
  displayName: Queue
  shortDescription: Persisted queue address
  resourceLimits:
    broker: 0.5
    router: 0.1
  addressType: queue
---
apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: default-anycast
  namespace: enmasse-infra
spec:
  displayName: Anycast
  shortDescription: Volatile anycast address
  resourceLimits:
    router: 0.1
  addressType: anycast
---
apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: default-multicast
  namespace: enmasse-infra
spec:
  displayName: Multicast
  shortDescription: Volatile multicast address
  resourceLimits:
    router: 0.2
  addressType: multicast
