apiVersion: admin.enmasse.io/v1beta1
kind: ConsoleService
metadata:
  name: console
spec:
  discoveryMetadataURL: https://keycloak.devlocal/auth/realms/k8s/.well-known/openid-configuration
  oauthClientSecret:
    name: oidc-secret
  scope: openid email
  oauthProxy:
    extraArgs:
      - "-ssl-insecure-skip-verify"
