apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sandbox-tenant
rules:
  - apiGroups: [ "enmasse.io" ]
    resources: [ "addresses", "addressspaces" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
