global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_auth_username: 'ulf.lilleengen@gmail.com'
  smtp_from: 'EnMasse Sandbox Alerts <alerts@sandbox.enmasse.io>'
route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'me'
receivers:
- name: 'me'
  email_configs:
  - to: 'ulf.lilleengen@gmail.com'
