apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    prometheus: prometheus
spec:
  replicas: 1
  retention: 4w
  initContainers:
    - name: prometheus-data-permission-fix
      image: busybox
      command: ["/bin/chmod","-R","777", "/prometheus"]
      volumeMounts:
      - name: prometheus-prometheus-db
        mountPath: /prometheus
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10G
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  podMonitorNamespaceSelector: {}
  ruleNamespaceSelector: {}
  ruleSelector: {}
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-operated
      port: web
