kind: IoTConfig
apiVersion: iot.enmasse.io/v1alpha1
metadata:
  name: default
spec:
  # ...
  services:
    deviceRegistry:
      jdbc:
        server:
          # This example only focuses on the aspect of the "external" JDBC device registry.
          # It is not a complete configuration.
          external:
            devices:
              mode: TABLE
            url: jdbc:h2:tcp://h2.device-registry-storage.svc//data/device-registry
            username: registry
            password: user12
            extensions:
              - container:
                  name: ext-add-h2-driver
                  image: quay.io/ctronenmassetesting/h2-extension:latest
                  imagePullPolicy: Always
                  volumeMounts:
                  - name: extensions
                    mountPath: /ext
