kind: Deployment
apiVersion: apps/v1
metadata:
  name: enmasse-operator
  labels:
    app: enmasse
    name: enmasse-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: enmasse-operator
  template:
    metadata:
      labels:
        app: enmasse
        name: enmasse-operator
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: node-role.enmasse.io/operator-infra
                    operator: In
                    values:
                      - "true"
      serviceAccountName: enmasse-operator
      containers:
      - name: controller
        image: docker.io/lulf/controller-manager:latest
        imagePullPolicy: Always
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IOT_CONFIG_NAME
          value: "default"
        - name: OPERATOR_NAME
          value: "enmasse-operator"
        - name: IMAGE_PULL_POLICY
          value: "Always"
        - name: CONTROLLER_DISABLE_ALL
          value: "true"
        - name: CONTROLLER_ENABLE_UPGRADER
          value: "true"
        - name: CONTROLLER_ENABLE_IOT_PROJECT
          value: "true"
        - name: CONTROLLER_ENABLE_IOT_CONFIG
          value: "true"
        - name: CONTROLLER_ENABLE_AUTHENTICATION_SERVICE
          value: "true"
        - name: CONTROLLER_ENABLE_ADDRESS_SPACE_CONTROLLER
          value: "true"
        - name: CONTROLLER_ENABLE_MESSAGING_USER
          value: "true"
        - name: ADDRESS_SPACE_CONTROLLER_IMAGE
          value: docker.io/lulf/address-space-controller:latest
        - name: CONTROLLER_MANAGER_IMAGE
          value: docker.io/lulf/controller-manager:latest
        - name: IOT_AUTH_SERVICE_IMAGE
          value: docker.io/lulf/iot-auth-service:latest
        - name: IOT_DEVICE_REGISTRY_FILE_IMAGE
          value: docker.io/lulf/iot-device-registry-file:latest
        - name: IOT_DEVICE_REGISTRY_INFINISPAN_IMAGE
          value: docker.io/lulf/iot-device-registry-infinispan:latest
        - name: IOT_HTTP_ADAPTER_IMAGE
          value: docker.io/lulf/iot-http-adapter:latest
        - name: IOT_MQTT_ADAPTER_IMAGE
          value: docker.io/lulf/iot-mqtt-adapter:latest
        - name: IOT_LORAWAN_ADAPTER_IMAGE
          value: docker.io/lulf/iot-lorawan-adapter:latest
        - name: IOT_SIGFOX_ADAPTER_IMAGE
          value: docker.io/lulf/iot-sigfox-adapter:latest
        - name: IOT_TENANT_CLEANER_IMAGE
          value: docker.io/lulf/iot-tenant-cleaner:latest
        - name: IOT_TENANT_SERVICE_IMAGE
          value: docker.io/lulf/iot-tenant-service:latest
        - name: IOT_PROXY_CONFIGURATOR_IMAGE
          value: docker.io/lulf/iot-proxy-configurator:latest
        - name: ROUTER_IMAGE
          value: quay.io/interconnectedcloud/qdrouterd:1.10.0
        - name: STANDARD_CONTROLLER_IMAGE
          value: docker.io/lulf/standard-controller:latest
        - name: AGENT_IMAGE
          value: docker.io/lulf/agent:latest
        - name: BROKER_IMAGE
          value: quay.io/enmasse/artemis-base:2.11.0
        - name: BROKER_PLUGIN_IMAGE
          value: docker.io/lulf/broker-plugin:latest
        - name: TOPIC_FORWARDER_IMAGE
          value: docker.io/lulf/topic-forwarder:latest
        - name: MQTT_GATEWAY_IMAGE
          value: docker.io/lulf/mqtt-gateway:latest
        - name: MQTT_LWT_IMAGE
          value: docker.io/lulf/mqtt-lwt:latest
        - name: NONE_AUTHSERVICE_IMAGE
          value: docker.io/lulf/none-authservice:latest
        - name: KEYCLOAK_IMAGE
          value: quay.io/enmasse/keycloak-openshift:4.8.3.Final
        - name: KEYCLOAK_PLUGIN_IMAGE
          value: docker.io/lulf/keycloak-plugin:latest
        - name: CONTROLLER_ENABLE_CONSOLE_SERVICE
          value: "true"
        - name: CONSOLE_INIT_IMAGE
          value: "docker.io/lulf/console-init:latest"
        - name: CONSOLE_SERVER_IMAGE
          value: "docker.io/lulf/console-server:latest"
        - name: CONSOLE_PROXY_OPENSHIFT_IMAGE
          value: "openshift/oauth-proxy:latest"
        - name: CONSOLE_PROXY_KUBERNETES_IMAGE
          value: "quay.io/pusher/oauth2_proxy:latest"
        - name: CONSOLE_LINK_SECTION_NAME
          value: "Messaging"
        - name: CONSOLE_LINK_NAME
          value: "EnMasse Console"
        - name: CONSOLE_LINK_IMAGE_URL
          value: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iNzlweCIgaGVpZ2h0PSI3OXB4IiB2aWV3Qm94PSIwIDAgNzkgNzkiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+CiAgICA8IS0tIEdlbmVyYXRvcjogU2tldGNoIDQyICgzNjc4MSkgLSBodHRwOi8vd3d3LmJvaGVtaWFuY29kaW5nLmNvbS9za2V0Y2ggLS0+CiAgICA8dGl0bGU+dmVyc2lvbnM8L3RpdGxlPgogICAgPGRlc2M+Q3JlYXRlZCB3aXRoIFNrZXRjaC48L2Rlc2M+CiAgICA8ZGVmcz48L2RlZnM+CiAgICA8ZyBpZD0iUGFnZS0xIiBzdHJva2U9Im5vbmUiIHN0cm9rZS13aWR0aD0iMSIgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj4KICAgICAgICA8ZyBpZD0idmVyc2lvbnMiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0zMDguMDAwMDAwLCAtNzIuMDAwMDAwKSI+CiAgICAgICAgICAgIDxlbGxpcHNlIGlkPSJDb21iaW5lZC1TaGFwZS1Db3B5LTIiIGZpbGw9IiMwMDQ5OUUiIGN4PSIzNDcuNSIgY3k9IjExMS41IiByeD0iMjQuNSIgcnk9IjI0LjUiPjwvZWxsaXBzZT4KICAgICAgICAgICAgPHBhdGggZD0iTTMzOSwxMDIuNjkxMDE0IEMzMzksMTAyLjY5MTAxNCAzNDIuNjkwMjE1LDk0LjQxMDUzMjMgMzUwLjIwNTY1MSwxMDAuOTM1OTEyIEwzNTEuMDE1Njk5LDEwMS43NDU5NTkgQzM1MS4wMTU2OTksMTAxLjc0NTk1OSAzNTIuNzI1Nzk4LDEwMy41MDEwNjEgMzUzLjQ0NTg0LDEwMy41MDEwNjEgQzM1NC4xNjU4ODIsMTAzLjUwMTA2MSAzNTQuMjU1ODg3LDEwMy40MTEwNTYgMzU1Ljk2NTk4NiwxMDEuNzAwOTU2IEMzNTcuNjc2MDg2LDk5Ljk5MDg1NjggMzU3LjQwNjA3LDEwMC4wMzU4NTkgMzU5Ljg4MTIxNCw5Ny43ODU3Mjg2IEMzNjIuMzU2MzU4LDk1LjUzNTU5NzcgMzY1LjY3MTUyMSw5My45MzA1MzQ0IDM2NS42NzE1MjEsOTMuOTMwNTM0NCBDMzY1LjY3MTUyMSw5My45MzA1MzQ0IDM2Ny4yOTE2MTUsOTIuOTEwNDE1MSAzNzAuMjYxNzg4LDkyLjE2MDQwMTUgQzM3My4yMzE5Niw5MS40MTAzODc5IDM3Ny40MDk3MzMsOTAuNjUyODEzOSAzODIsOTEuMTcwMzQ0IEMzODIsOTEuMTcwMzQ0IDM4MC4xMzIzOTEsOTIuMjUwNDA2NyAzNzcuOTI3MjYzLDk4Ljk1NTc5NjYgQzM3NS43MjIxMzUsMTA1LjY2MTE4NiAzNzQuNTA3MDY0LDEwNy43MzEzMDcgMzc0LjUwNzA2NCwxMDcuNzMxMzA3IEMzNzQuNTA3MDY0LDEwNy43MzEzMDcgMzcxLjg1MTkxLDExMy4zNTY2MzQgMzY1LjQ2MTUzOCwxMTQuNTcxNzA0IEMzNjUuNDYxNTM4LDExNC41NzE3MDQgMzY4LjY1NjcyNCwxMTguMzk2OTI3IDM3OS45OTczODQsMTE3LjEzNjg1NCBDMzc5Ljk5NzM4NCwxMTcuMTM2ODU0IDM1OC4wODExMDksMTMxLjE3NzY3IDM0OC4yNzA1MzksMTE0Ljg0MTcyIEMzNDguMDQ4OTQ2LDExNC4zNDQyNjEgMzQ1Ljg0OTM5OCwxMTAuMDI1NDUgMzQ1LjMwMDM2NiwxMDguMjExMzA1IEMzNDQuNjEwMjk2LDEwNS45MzEyMDIgMzQ0LjMwOTEzOSwxMDUuMTI1Mzg1IDM0My4yOTAyNzksMTA0LjE2MTA2OSBDMzQwLjc3MDEzMywxMDEuNzc1OTMxIDMzOSwxMDIuNjkxMDE0IDMzOSwxMDIuNjkxMDE0IiBpZD0iRmlsbC0xLUNvcHktNyIgZmlsbD0iIzc1QTBEMyI+PC9wYXRoPgogICAgICAgIDwvZz4KICAgIDwvZz4KPC9zdmc+"
        - name: ENABLE_MONITORING
          value: "true"
