apiVersion: admin.enmasse.io/v1beta1
kind: ConsoleService
metadata:
  name: console
  namespace: enmasse-infra
spec:
  discoveryMetadataURL: https://auth.sandbox.enmasse.io/auth/realms/k8s/.well-known/openid-configuration
  certificateSecret:
    name: console-cert
  oauthClientSecret:
    name: oidc-secret
  scope: openid email
  impersonation:
    userHeader: "X-Forwarded-Email"
  oauthProxy:
    extraArgs:
      - "-ssl-insecure-skip-verify"
      - "-skip-provider-button"

