apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: default
  namespace: enmasse-infra
spec:
  admin:
    resources:
      memory: 256Mi
  router:
    linkCapacity: 6
    resources:
      memory: 128Mi
  broker:
    resources:
      memory: 512Mi
      storage: 1Gi
    addressFullPolicy: FAIL

