apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: default
  namespace: enmasse-infra
spec:
  admin:
    resources:
      memory: 256Mi
  router:
    linkCapacity: 4
    resources:
      memory: 128Mi
    policy:
      maxConnections: 4
      maxSendersPerConnection: 2
      maxReceiversPerConnection: 2
      maxSessionsPerConnection: 2
  broker:
    resources:
      memory: 512Mi
      storage: 1Gi
    addressFullPolicy: FAIL

