apiVersion: admin.enmasse.io/v1beta2
kind: AddressSpacePlan
metadata:
  name: default
  namespace: enmasse-infra
spec:
  infraConfigRef: default
  displayName: Default
  shortDescription: Plan allowing for 1 router and 1 broker
  resourceLimits:
    broker: 1.0
    router: 1.0
    aggregate: 2.0
  addressSpaceType: standard
  addressPlans:
    - small-queue
    - small-topic
    - small-subscription
    - small-anycast
    - small-multicast

