apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: messaging-cert
  namespace: enmasse-infra
spec:
  secretName: messaging-cert
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-dns
  commonName: messaging.sandbox.enmasse.io
  dnsNames:
  - messaging.sandbox.enmasse.io
  - "*.messaging.sandbox.enmasse.io"
  - messaging-wss.sandbox.enmasse.io
  - "*.messaging-wss.sandbox.enmasse.io"
