apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: small-queue
  namespace: enmasse-infra
spec:
  displayName: Small Queue
  shortDescription: Address with queue semantics
  resources:
    broker: 0.5
    router: 0.1
  addressType: queue

