apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: small-anycast
  namespace: enmasse-infra
spec:
  displayName: Small Anycast
  shortDescription: Address with anycast semantics
  resources:
    router: 0.1
  addressType: anycast

