apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sandbox.enmasse.io:sandbox-api
rules:
  - apiGroups: [ "sandbox.enmasse.io" ]
    resources: [ "sandboxtenants" ]
    verbs: [ "create", "update", "patch", "get", "list", "watch", "delete" ]
