apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sandboxtenants.sandbox.strimzi.io
spec:
  group: sandbox.strimzi.io
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
              - subject
            properties:
              subject:
                type: string
          status:
            type: object
            properties:
              provisionTimestamp:
                type: string
              expirationTimestamp:
                type: string
              bootstrap:
                type: string
              brokers:
                type: array
                items:
                  type: string
              namespace:
                type: string
  scope: Cluster
  names:
    plural: sandboxtenants
    singular: sandboxtenant
    kind: SandboxTenant
