apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "sandbox.enmasse.io:sandbox-operator"
  labels:
    app: enmasse
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sandbox.enmasse.io:sandbox-operator
subjects:
- kind: ServiceAccount
  name: sandbox-operator
  namespace: sandbox
